# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10-browsers

jobs:
  build: 
    <<: *defaults 
    steps: 
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: sudo npm i -g npm
      - run: npm ci
      - run: npm run build
      - run: 
          name: Jest Tests
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run: sudo npm i -g pouchdb-server
      - run: (pouchdb-server --in-memory --port 5984 &) && (cd build && python -m SimpleHTTPServer 3000 >> /dev/null 2>&1 &) &&  (npm run test-e2e-report)
      - store_test_results:
          path: /tmp/test-results
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
                  - /root/.npm

workflows:
  version: 2
  build:
    jobs:
      - build
